

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/contacts?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: yyc960817
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10s


# 解决列名(underscore)与字段名(camelCase)的转换问题
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#logging:
#  level:
#    root: debug
